# Generated by Django 5.2.1 on 2026-05-17 14:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGrooming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('street', models.TextField()),
                ('area', models.TextField()),
                ('city', models.TextField()),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('review_sum', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='e.g. {"saturday": {"open": "09:00", "close": "18:00"}, ...}')),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroomingServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroomingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_grooming_appointments', to=settings.AUTH_USER_MODEL)),
                ('training_grooming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_grooming_appointments', to='training_grooming.traininggrooming')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroomingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_grooming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_grooming_reviews', to='training_grooming.traininggrooming')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_grooming_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'training_grooming')},
            },
        ),
        migrations.CreateModel(
            name='TrainingGroomingReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_grooming_review_replies', to='training_grooming.traininggroomingreview')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_grooming_review_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='traininggrooming',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='training_grooming', to='training_grooming.traininggroomingservices'),
        ),
        migrations.AddField(
            model_name='traininggrooming',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='training_grooming', to='training_grooming.traininggroomingtag'),
        ),
    ]
