# Generated by Django 5.2.1 on 2026-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"saturday": {"open": "09:00", "close": "18:00"}, ...}'),
        ),
    ]
