# Generated by Django 5.2.1 on 2026-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='hospital',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='review_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
