# Generated by Django 5.2.1 on 2026-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount ($)')], default='percentage', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_cap', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order subtotal required to apply this coupon', max_digits=10)),
                ('max_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount allowed (especially for percentage discounts)', max_digits=10, null=True)),
                ('open_date', models.DateTimeField(help_text='When this coupon becomes active/valid')),
                ('close_date', models.DateTimeField(help_text='When this coupon expires/closes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
