# Generated by Django 5.2.1 on 2026-05-17 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('pet_type', models.CharField(max_length=100)),
                ('age_in_months', models.PositiveIntegerField(help_text='Age in months (e.g., 17 = 1 year 5 months)')),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('is_healthy', models.BooleanField(default=True)),
                ('is_neutered', models.BooleanField(default=False)),
                ('vaccination_status', models.BooleanField(default=False)),
                ('adoption_status', models.BooleanField(default=False)),
                ('user_nid', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_adoptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
