# Generated by Django 5.2.1 on 2026-05-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadoption',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
