# Generated by Django 6.1 on 2026-08-11 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption', '0002_petadoption_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadoption',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
