# Generated by Django 5.2.1 on 2026-08-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.coupon'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by_admin',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
